# ruff: noqa: E501, T201


from pathlib import Path

import openpyxl
from docx import Document


def generate_mock_data() -> None:
    docs_dir = Path("data/docs")
    docs_dir.mkdir(parents=True, exist_ok=True)

    # 40 records to generate
    records = [
        # Empenho (10 records)
        (
            101,
            "POP",
            "Empenho - Inclusão Ordinário",
            "Empenho",
            "Inclusão",
            "Ordinário",
            "",
            "incluir; ordinario; novo empenho",
            "Passo a passo para inclusão de um empenho do tipo ordinário.",
            "",
            "POP_101__empenho-inclusao-ordinario.docx",
        ),
        (
            102,
            "POP",
            "Empenho - Inclusão Global",
            "Empenho",
            "Inclusão",
            "Global",
            "",
            "incluir; global",
            "Procedimento para gerar um empenho global com múltiplas parcelas.",
            "",
            "POP_102__empenho-inclusao-global.docx",
        ),
        (
            103,
            "POP",
            "Empenho - Inclusão Estimativa",
            "Empenho",
            "Inclusão",
            "Estimativa",
            "",
            "incluir; estimativa; serviços",
            "Como realizar a inclusão de um empenho por estimativa.",
            "",
            "POP_103__empenho-inclusao-estimativa.docx",
        ),
        (
            104,
            "VIDEO",
            "Visão Geral dos Tipos de Empenho",
            "Empenho",
            "Conceitos",
            "",
            "",
            "tipos; introdução; teoria",
            "Vídeo explicativo sobre as diferenças entre empenho ordinário, global e por estimativa.",
            "https://youtube.com/watch?v=emp_vis_1",
            "",
        ),
        (
            105,
            "POP",
            "Empenho - Reforço",
            "Empenho",
            "Alteração",
            "Reforço",
            "",
            "reforçar; aumentar valor",
            "Instruções para realizar o reforço de saldo de um empenho existente.",
            "",
            "POP_105__empenho-reforco.docx",
        ),
        (
            106,
            "POP",
            "Empenho - Anulação Total",
            "Empenho",
            "Cancelamentos",
            "Anulação",
            "Total",
            "anular; cancelar; excluir",
            "Como anular totalmente o saldo de um empenho.",
            "",
            "POP_106__empenho-anulacao-total.docx",
        ),
        (
            107,
            "POP",
            "Empenho - Anulação Parcial",
            "Empenho",
            "Cancelamentos",
            "Anulação",
            "Parcial",
            "anular; parcial; reduzir",
            "Como realizar a anulação parcial (estorno parcial) do empenho.",
            "",
            "POP_107__empenho-anulacao-parcial.docx",
        ),
        (
            108,
            "VIDEO",
            "Como Anular um Empenho na Prática",
            "Empenho",
            "Cancelamentos",
            "Anulação",
            "",
            "vídeo; anulação; prática",
            "Tutorial em vídeo demonstrando a anulação total e parcial.",
            "https://youtube.com/watch?v=emp_anula_2",
            "",
        ),
        (
            109,
            "POP",
            "Empenho - Consulta de Saldo",
            "Empenho",
            "Consultas",
            "Saldo",
            "",
            "ver saldo; consulta; relatorio",
            "Passo a passo para consultar os saldos e o histórico de execuções do empenho.",
            "",
            "POP_109__empenho-consulta-saldo.docx",
        ),
        (
            110,
            "POP",
            "Empenho - Histórico de Alterações",
            "Empenho",
            "Consultas",
            "Histórico",
            "",
            "auditoria; historico; alteracoes",
            "Como verificar quem realizou alterações em um empenho específico.",
            "",
            "POP_110__empenho-historico.docx",
        ),
        # Liquidação (10 records)
        (
            201,
            "POP",
            "Liquidação - Inclusão Material de Consumo",
            "Liquidação",
            "Inclusão",
            "Material",
            "Consumo",
            "liquidar; consumo; almoxarifado",
            "Procedimento para liquidar notas fiscais de material de consumo.",
            "",
            "POP_201__liq-material-consumo.docx",
        ),
        (
            202,
            "POP",
            "Liquidação - Inclusão Material Permanente",
            "Liquidação",
            "Inclusão",
            "Material",
            "Permanente",
            "liquidar; permanente; patrimonio",
            "Procedimento para liquidar notas fiscais de material permanente (bens).",
            "",
            "POP_202__liq-material-permanente.docx",
        ),
        (
            203,
            "POP",
            "Liquidação - Inclusão de Serviços",
            "Liquidação",
            "Inclusão",
            "Serviços",
            "",
            "liquidar; serviços; terceiros",
            "Como realizar a liquidação de notas fiscais ou faturas de prestação de serviços.",
            "",
            "POP_203__liq-servicos.docx",
        ),
        (
            204,
            "VIDEO",
            "Atesto e Liquidação: Entenda o Fluxo",
            "Liquidação",
            "Conceitos",
            "Fluxo",
            "",
            "atesto; recebimento; teoria",
            "Explicação do fluxo completo desde o atesto da NF até a liquidação no sistema.",
            "https://youtube.com/watch?v=liq_fluxo_1",
            "",
        ),
        (
            205,
            "POP",
            "Liquidação - Inclusão Folha de Pagamento",
            "Liquidação",
            "Inclusão",
            "Folha",
            "",
            "liquidar; folha; salarios",
            "Procedimentos específicos para inclusão da liquidação da folha de pagamento.",
            "",
            "POP_205__liq-folha.docx",
        ),
        (
            206,
            "POP",
            "Liquidação - Estorno Total",
            "Liquidação",
            "Estorno",
            "Total",
            "",
            "estornar; cancelar; erro",
            "Passo a passo para estornar uma nota de liquidação lançada indevidamente.",
            "",
            "POP_206__liq-estorno-total.docx",
        ),
        (
            207,
            "POP",
            "Liquidação - Estorno Parcial",
            "Liquidação",
            "Estorno",
            "Parcial",
            "",
            "estornar; ajuste; correção",
            "Como corrigir parcialmente valores de uma nota de liquidação via estorno.",
            "",
            "POP_207__liq-estorno-parcial.docx",
        ),
        (
            208,
            "VIDEO",
            "Erros Comuns na Liquidação e Como Corrigi-los",
            "Liquidação",
            "Estorno",
            "Exceções",
            "",
            "erros; solução; ajuda; vídeo",
            "Resolução de problemas frequentes enfrentados na tela de liquidação.",
            "https://youtube.com/watch?v=liq_erros_2",
            "",
        ),
        (
            209,
            "POP",
            "Liquidação - Inclusão Adiantamento",
            "Liquidação",
            "Inclusão",
            "Adiantamento",
            "",
            "suprimento; fundos; viagens",
            "Regras para liquidação de empenhos de suprimento de fundos/adiantamento.",
            "",
            "POP_209__liq-adiantamento.docx",
        ),
        (
            210,
            "POP",
            "Liquidação - Consulta de Notas",
            "Liquidação",
            "Consultas",
            "Notas",
            "",
            "buscar; pesquisar; notas liquidação",
            "Como consultar a lista e a situação de notas de liquidação geradas.",
            "",
            "POP_210__liq-consulta-notas.docx",
        ),
        # Pagamento (10 records)
        (
            301,
            "POP",
            "Pagamento - Ordem Bancária (OB)",
            "Pagamento",
            "Inclusão",
            "Ordem Bancária",
            "Fornecedor",
            "pagar; ob; transferência",
            "Geração de Ordem Bancária para pagamento de fornecedores.",
            "",
            "POP_301__pag-ob-fornecedor.docx",
        ),
        (
            302,
            "POP",
            "Pagamento - Programação de Desembolso (PD)",
            "Pagamento",
            "Programação",
            "Inclusão",
            "",
            "programar; pd; fluxo de caixa",
            "Como incluir a Programação de Desembolso antes do pagamento efetivo.",
            "",
            "POP_302__pag-pd.docx",
        ),
        (
            303,
            "VIDEO",
            "Fluxo PD e OB: O que vem primeiro?",
            "Pagamento",
            "Conceitos",
            "Fluxo",
            "",
            "teoria; ordem; processo",
            "Vídeo aula sobre o cronograma de programação e ordem de pagamento.",
            "https://youtube.com/watch?v=pag_fluxo_1",
            "",
        ),
        (
            304,
            "POP",
            "Pagamento - Retenção de Tributos (IR, INSS)",
            "Pagamento",
            "Retenções",
            "Tributos Federais",
            "",
            "reter; imposto; irrf; inss",
            "Guia para registrar e destacar retenções tributárias no momento do pagamento.",
            "",
            "POP_304__pag-retencoes-federais.docx",
        ),
        (
            305,
            "POP",
            "Pagamento - Retenção de ISS",
            "Pagamento",
            "Retenções",
            "Tributos Municipais",
            "ISS",
            "reter; imposto municipal; issqn",
            "Como destacar a retenção do Imposto Sobre Serviços (ISS).",
            "",
            "POP_305__pag-retencoes-iss.docx",
        ),
        (
            306,
            "POP",
            "Pagamento - Cancelamento de OB",
            "Pagamento",
            "Cancelamentos",
            "OB",
            "",
            "cancelar pagamento; estorno bancario",
            "Como registrar o cancelamento ou a devolução de uma Ordem Bancária rejeitada.",
            "",
            "POP_306__pag-cancelamento-ob.docx",
        ),
        (
            307,
            "POP",
            "Pagamento - Pagamento de Pessoal",
            "Pagamento",
            "Inclusão",
            "Folha",
            "",
            "ob folha; salarios; servidores",
            "Rotina para a efetivação do pagamento em lote de servidores.",
            "",
            "POP_307__pag-ob-folha.docx",
        ),
        (
            308,
            "VIDEO",
            "Tratando Retorno de Remessa Bancária",
            "Pagamento",
            "Retorno Bancário",
            "",
            "",
            "arquivo retorno; erro banco; vídeo",
            "Passo a passo processando o arquivo de retorno de pagamentos enviados ao banco.",
            "https://youtube.com/watch?v=pag_retorno_2",
            "",
        ),
        (
            309,
            "POP",
            "Pagamento - Consulta de Situação",
            "Pagamento",
            "Consultas",
            "Situação",
            "",
            "ver status; pago; pendente",
            "Como saber se o fornecedor já foi pago ou se está pendente.",
            "",
            "POP_309__pag-consulta-situacao.docx",
        ),
        (
            310,
            "POP",
            "Pagamento - Relatório de Empenhos a Pagar",
            "Pagamento",
            "Relatórios",
            "Pendentes",
            "",
            "relatorio; a pagar; divida",
            "Emissão do relatório de restos a pagar e empenhos liquidados não pagos.",
            "",
            "POP_310__pag-relatorio-pendentes.docx",
        ),
        # Contabilidade (10 records)
        (
            401,
            "POP",
            "Contabilidade - Conciliação Bancária",
            "Contabilidade",
            "Rotinas Mensais",
            "Conciliação",
            "Bancos",
            "conciliar; extrato; fechamento",
            "Como realizar a conciliação entre as contas do GRP e os extratos bancários.",
            "",
            "POP_401__cont-conciliacao.docx",
        ),
        (
            402,
            "POP",
            "Contabilidade - Lançamentos Manuais (Partida Dobrada)",
            "Contabilidade",
            "Lançamentos",
            "Manuais",
            "",
            "partida dobrada; debito credito; diario",
            "Guia para realizar lançamentos contábeis típicos (débito/crédito) manuais.",
            "",
            "POP_402__cont-lancamentos.docx",
        ),
        (
            403,
            "VIDEO",
            "Entendendo o Plano de Contas Aplicado",
            "Contabilidade",
            "Conceitos",
            "Plano de Contas",
            "",
            "pcasp; teoria; contas; vídeo",
            "Apresentação estrutural do PCASP utilizado no sistema.",
            "https://youtube.com/watch?v=cont_pcasp_1",
            "",
        ),
        (
            404,
            "POP",
            "Contabilidade - Encerramento de Exercício",
            "Contabilidade",
            "Rotinas Anuais",
            "Encerramento",
            "",
            "fechar ano; balanço; virada",
            "Procedimentos necessários para o fechamento do exercício fiscal no GRP.",
            "",
            "POP_404__cont-encerramento.docx",
        ),
        (
            405,
            "POP",
            "Contabilidade - Abertura de Exercício",
            "Contabilidade",
            "Rotinas Anuais",
            "Abertura",
            "",
            "abrir ano; saldo inicial; janeiro",
            "Passos para iniciar a contabilidade em um novo ano civil.",
            "",
            "POP_405__cont-abertura.docx",
        ),
        (
            406,
            "POP",
            "Contabilidade - Relatório Balanço Patrimonial",
            "Contabilidade",
            "Relatórios",
            "Demonstrações",
            "Balanço",
            "emitir balanco; ativo; passivo",
            "Como extrair o relatório consolidado do Balanço Patrimonial.",
            "",
            "POP_406__cont-balanco-patrimonial.docx",
        ),
        (
            407,
            "POP",
            "Contabilidade - Relatório Demonstração de Variações",
            "Contabilidade",
            "Relatórios",
            "Demonstrações",
            "VPA/VPD",
            "dve; variaçoes; receita despesa",
            "Emissão da Demonstração das Variações Patrimoniais.",
            "",
            "POP_407__cont-dve.docx",
        ),
        (
            408,
            "VIDEO",
            "Auditoria Contábil: Erros e Ajustes",
            "Contabilidade",
            "Consultas",
            "Auditoria",
            "",
            "auditar; inconsistencias; vídeo",
            "Dicas em vídeo de como achar e arrumar inconsistências entre os módulos.",
            "https://youtube.com/watch?v=cont_auditoria_2",
            "",
        ),
        (
            409,
            "POP",
            "Contabilidade - Consulta Razão Contábil",
            "Contabilidade",
            "Consultas",
            "Livros",
            "Razão",
            "livro razao; conta; detalhe",
            "Como pesquisar o detalhamento do Razão Contábil de uma conta específica.",
            "",
            "POP_409__cont-razao.docx",
        ),
        (
            410,
            "POP",
            "Contabilidade - Consulta Diário Contábil",
            "Contabilidade",
            "Consultas",
            "Livros",
            "Diário",
            "livro diario; cronologico",
            "Impressão e consulta do Livro Diário com toda a movimentação.",
            "",
            "POP_410__cont-diario.docx",
        ),
    ]

    # Write XLSX
    xlsx_file = Path("data/imports/materials.xlsx")
    wb = openpyxl.Workbook()
    ws = wb.active
    if ws is None:
        raise RuntimeError("No active worksheet found")

    ws.append(
        [
            "id",
            "type",
            "title",
            "module",
            "theme",
            "subtheme",
            "subsubtheme",
            "keywords",
            "summary",
            "source_url",
            "blob_path",
        ]
    )
    for r in records:
        ws.append(r)

        # If it's a POP, generate a real docx file
        if r[1] == "POP" and r[10]:
            doc_name = str(r[10])
            doc_path = docs_dir / doc_name

            # Create a simple word doc
            document = Document()
            document.add_heading(str(r[2]), 0)  # Title
            document.add_heading(f"Módulo: {r[3]}", level=1)

            p = document.add_paragraph()
            p.add_run("Resumo do Procedimento: ").bold = True
            p.add_run(str(r[8]))

            document.add_heading("Passo a Passo", level=2)
            document.add_paragraph(
                "1. Acesse o sistema GRP e faça login com suas credenciais.",
                style="List Number",
            )
            document.add_paragraph(
                "2. Navegue até o menu principal correspondente ao módulo.",
                style="List Number",
            )
            document.add_paragraph(
                "3. Preencha os campos obrigatórios conforme descrito no manual geral.",
                style="List Number",
            )
            document.add_paragraph(
                "4. Clique no botão 'Salvar' ou 'Confirmar' para registrar a operação.",
                style="List Number",
            )
            document.add_paragraph(
                "5. Verifique a mensagem de sucesso e anote o número do registro gerado.",
                style="List Number",
            )

            document.add_paragraph("\n[Fim do Documento Simulado - MVP]")

            document.save(str(doc_path))

    wb.save(xlsx_file)


if __name__ == "__main__":
    generate_mock_data()
    print("XLSX com 40 registros gerado e arquivos .docx criados em data/docs/")
